name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        name: Build
        with:
          gradle-version: current
          arguments: build
      - name: List
        run: ls -la build/reports/jacoco/test/jacocoTestReport.xml
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
      - name: List
        run: ls -la build/reports/jacoco/test/jacocoTestReport.xml